package duke_command;

public enum Command {
    COMMAND_EXIT,
    COMMAND_LIST_STORED_TASKS,
    COMMAND_SET_TASK_DONE,
    COMMAND_ADD_TODO,
    COMMAND_ADD_DEADLINE,
    COMMAND_ADD_EVENT,
    COMMAND_INSTRUCTIONS,
    COMMAND_DELETE,
    COMMAND_SAVE,
    COMMAND_LOAD;
}
